# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wXUOTWcq3jn4nxmPMmyH-6bRvYmMmmiA
"""

import pickle

with open('classifier.pkl','rb') as file:
  clf = pickle.load(file)

prediction = clf.predict([[1]])

prediction